global using Bogus;
global using Common.Models;
global using Common.Entities;
global using Core;
global using DataAccess;
global using Microsoft.EntityFrameworkCore;
global using NUnit.Framework;
global using Test.Setup;
global using Test.Setup.TestData;